### PR TITLE
Kinetic devel

### PR DESCRIPTION
**Pull request by drchrislewis**
@shaun-edwards Please review or assign someone. This kinetic-devel version may be tested using the kinetic-devel branch of the industrial_calibration_tutorials : calibrate_from_images.launch example. Also, if you run the dynamic reconfigure gui you can break the calibration by adjusting the parameters away from their defaults. 
I believe #89 is addressed 
#45 is addressed by removing mono_ex_cal from the CMakeList.txt. It was one of the original examples developed to use Ceres-solver and is neither documented nor used anymore.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
I'm testing this right now!

**Comment by VictorLamoine** [comment]
```cpp
[ INFO] [1489662006.524088584]: Ready to take commands for planning group manipulator.
[ERROR] [1489662006.560440767]: Can't parse node[moving_cameras]
terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  yaml-cpp: error at line 0, column 0: invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
[calibration_service_node-12] process has died [pid 14255, exit code -6, cmd /home/victor/code/catkin_workspace/devel/lib/industrial_extrinsic_cal/service_node __name:=calibration_service_node __log:=/home/victor/.ros/log/b4e1cd62-0a37-11e7-83bb-34e6d766b009/calibration_service_node-12.log].
log file: /home/victor/.ros/log/b4e1cd62-0a37-11e7-83bb-34e6d766b009/calibration_service_node-12*.log

```

**Comment by drchrislewis** [comment]
@VictorLamoine The parser will work if one defines both moving and static targets and cameras, but just leave the node empty if there aren't any of that type. See example of syntax of yaml files in industrial_calibration_tutorials.

**Comment by VictorLamoine** [comment]
I'm using the same YAML files between Indigo and Kinetic and the node crashes in Kinetic.
Maybe it's not the same yaml-cpp version and there's been in change in the API?! I'll check again my files

**Pull request closed without merging**
