### PR TITLE
Kinetic

### PR DESCRIPTION
**Pull request by AustinDeric**
updates to build with ceres-solver from source.  Also fixes std namespace issues.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
:+1: for these changes.

Have you successfully used the extrinsic calibration package on Kinetic?
I have this issue:
https://github.com/ros-industrial/industrial_calibration/issues/89#issuecomment-279951061

**Comment by drchrislewis** [comment]
@gavanderhoorn 

I hope I did the right thing here. If not please provide some guidance. I understood the issue to be how do we handle the ceres-solver dep. There were comments about your pull stating that it depended on the side branch of ceres-solver and this was not advised. Now that ceres-solver has a package.xml file and seems to compile just fine under catkin, It makes sense to have a direct dependency on it. I believe Austin's latest PR makes it as easy as ever to install and compile.  I'm not confident. I haven't had much ROS time in the past few months, and I've completely neglected the calibration code.

**Comment by AustinDeric** [comment]
@VictorLamoine I will test it out and let you know.  Thanks for pointing out #89.  We are going to take a look at that and many of the others.

**Comment by gavanderhoorn** [comment]
I'm fine with using a source build of `ceres`. I'm guessing it got 'upgraded' to a catkin package because of Google using it in their `cartographer` and this was just easier.

I would just recommend to depend on a *specific version* of `ceres-solver`, and not track `master` branch.

Note btw that this means that the calibration pkgs will still not be releasable through the ROS buildfarm.

Note also that #85 was not my PR, but @mintar's.

**Comment by gavanderhoorn** [comment]
(final) note: now that `ceres-solver` is a catkin package, it should be relatively straightforward to release it - provided that its dependencies are available on all target platforms.

**Pull request merged**
