### PR TITLE
Port/robot cal tools

### PR DESCRIPTION
**Pull request by marip8**
This PR seeks to merge the revised calibration functionality of [`robot_cal_tools`](https://github.com/Jmeyer1292/robot_cal_tools) back into `industrial_calibration`. The contents of `robot_cal_tools` from [this commit](https://github.com/Jmeyer1292/robot_cal_tools/tree/2fd5b85de098fc2e97d06d51addd638304e0610e) have been collected into a single pure CMake package called `ical_core` which contains the core calibration definitions, optimizations, and perception capabilities as well as unit tests and real data examples.

It's been a long time coming, but this PR is the start of a larger refactor of `industrial_calibration` that will:
- revise the structure of the underlying calibration algorithms (this PR)
- revise the GUI interfaces for performing calibration
- revise the ROS1 interface
- create a ROS2 interface
- improve tools for integrating motion planning into the calibration data collection process

Future PRs will:
- Identify and port relevant optimization/perception capability from other packages in `industrial_calibration` to the `ical_core` package
- Remove packages in `industrial_calibration` that are superceded by `ical_core`
- Add calibration GUIs applications for each type supported calibration
- Update/add ROS1 and ROS2 interfaces

### CODE REVIEW

**Comment by marip8** [comment]
@jdlangs I updated this PR to remove the light dependency on Boost per our previous discussion

@Levi-Armstrong I updated CI to use Github Actions; is there something you need to do as a maintainer to get it to run for this PR, or will it need to be merged first?

**Comment by Levi-Armstrong** [comment]
I think it needs to be merged first but it should run on your branch.

**Comment by marip8** [comment]
Okay; I just opened a test PR [here](https://github.com/marip8/industrial_calibration/pull/1)

**Comment by marip8** [comment]
The [CI build](https://github.com/marip8/industrial_calibration/pull/1/checks) is finally successful

**Review by drchrislewis — APPROVED** [review]

**Pull request merged**
