### PR TITLE
Fixed build errors caused by 'isnan' not being declared in this scope

### PR DESCRIPTION
**Pull request by geoffreychiou**
This was the only thing that caused a build error when trying to build the kinetic branch.

### CODE REVIEW

**Comment by VictorLamoine** [comment]
:+1:

**Comment by shaun-edwards** [comment]
Travis is failing...looks like a missing Motoman dependency (it's not released in kinetic).  However, the build has passed in the past.  Does anyone know what changed?

**Comment by geoffreychiou** [comment]
I was able to get rid of the Motoman dependency but now it is complaining about how it can't find Ceres.

```
Errors << industrial_extrinsic_cal:cmake /root/catkin_ws/logs/industrial_extrinsic_cal/build.cmake.000.log
CMake Error at /root/catkin_ws/src/industrial_calibration/industrial_extrinsic_cal/CMakeLists.txt:26 (find_package):
  By not providing "FindCeres.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Ceres", but
  CMake did not find one.
  Could not find a package configuration file provided by "Ceres" with any of
  the following names:
    CeresConfig.cmake
    ceres-config.cmake
  Add the installation prefix of "Ceres" to CMAKE_PREFIX_PATH or set
  "Ceres_DIR" to a directory containing one of the above files.  If "Ceres"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by gavanderhoorn** [comment]
re: ceres: see #85.

re: motoman build error: well, you just removed the `run_depend`. Are there no launch files (fi) using files in `motoman` anymore?

**Pull request merged**
