### PR TITLE
Increase minimum CMake version to allow builds on Focal Fossa (Noetic)

### PR DESCRIPTION
**Pull request by ipa-nhg**
Related to https://github.com/ros-industrial/ros_industrial_issues/issues/67

### CODE REVIEW

**Comment by ipa-nhg** [comment]
I don't know if these changes are appropriate for the current state of the repository, please review and decide if it makes sense, otherwise you can close the PR.

**Comment by Levi-Armstrong** [comment]
I do not see any issues here.

**Comment by drchrislewis** [comment]
@ipa-nhg Its true the repository is undergoing some major cleanup and upgrades. However I see no harm in these changes. I've been compiling under 20.04 noetic for quite some time. cmake is not my strong suit, so any help is welcome. If you change the status from draft, I'll merge. Let me know if you need any help whatsoever regarding calibration.

**Comment by ipa-nhg** [comment]
Thanks @Levi-Armstrong @drchrislewis for your reviews and comments! I changed the status now.

**Pull request merged**
